//
// Created by 康晓宁 on 2022/2/4.
//

#ifndef PLAY_C_SRC_POINTER_INCLUDE_POINTER_PARAMETER_AS_RETURN_VALUE_H_
#define PLAY_C_SRC_POINTER_INCLUDE_POINTER_PARAMETER_AS_RETURN_VALUE_H_

void PointerParameterAsReturnValueExample();

#endif //PLAY_C_SRC_POINTER_INCLUDE_POINTER_PARAMETER_AS_RETURN_VALUE_H_
